<!--//HEADER-->
<?php $this->render('back/header'); ?>

<!--//MENU SDEBAR-->
<div class="span2 menu-sidebar">
    <?php $this->render('back/sidebar'); ?>
</div>

<!--//CONTENT -->
<div class="span10">
    <ul class="breadcrumb">
        <li><a href="#">Painel</a> <span class="divider">/</span></li>
        <li><a href="#">Licitações</a> <span class="divider">/</span></li>
        <li class="active">Modalidades</li>
    </ul>

    <div class="msgs">
        <?php \app\helpers\Message::get(); ?>
    </div>

        <div class="content">

            <div class="navbar-inner header-admin">

                <div class="nav-header">
                    <div class="local">
                        <h3>Modalidades</h3>
                    </div>

                    <div class="acoes">
                        <div class="btn-group">
                            <a href="<?php echo BASE; ?>/panel/modalidades/nova" class="btn btn-success btn-mini"><i class="icon-plus icon-white"></i> Novo</a>
                        </div>
                    </div>

                </div>
            </div><!--//header-admin-->

            <table class="table table-striped">
                <thead>
                <tr>
                    <th class="first">#</th>
                    <th>Nome</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($data as $item): ?>
                    <tr>
                        <td class="first"><span><?php echo $item->id; ?></td>
                        <td class="ctn"><?php echo $item->nome; ?></td>
                        <td class="btns-actions">
                            <a href="<?php echo BASE.'/panel/modalidades/nova/'.$item->id; ?>" class="btn btn-primary btn-mini"><i class="icon-edit icon-white"></i></a>
                            <a href="#del<?php echo $item->id; ?>" class="btn btn-danger btn-mini" data-toggle="modal"><i class="icon-trash icon-white"></i></a>

                            <div id="del<?php echo $item->id; ?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-header">
                                    <h3 id="myModalLabel">Exclusão de Registro</h3>
                                </div>
                                <div class="modal-body">
                                    <p>
                                        Deseja eliminar o registro <span class="badge badge-warning"><?php echo $item->nome; ?></span> do sistema?
                                    </p>
                                </div>
                                <div class="modal-footer">
                                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
                                    <a href="<?php echo BASE.'/panel/modalidades/del/'.$item->id; ?>" class="btn btn-danger">Continuar</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div><!--//content-->
</div>
<!--//CONTENT-->

<!--//FOOTER-->
<?php $this->render('back/footer'); ?>
