<!--//HEADER-->
<?php $this->render('back/header'); ?>

<!--//MENU SDEBAR-->
<div class="span2 menu-sidebar">
    <?php $this->render('back/sidebar'); ?>
</div>

<!--//CONTENT -->
<div class="span10">
    <ul class="breadcrumb">
        <li><a href="#">Painel</a> <span class="divider">/</span></li>
        <li><a href="#">Modalidades</a> <span class="divider">/</span></li>
        <li class="active">Nova</li>
    </ul>

    <div class="msgs">
        <?php \app\helpers\Message::get(); ?>
    </div>

        <div class="content">

            <div class="navbar-inner header-admin">
                <div class="nav-header">
                    <div class="local">
                        <h3>Nova modalidade</h3>
                    </div>

                    <div class="acoes">
                        <div class="btn-group">
                            <a href="<?php echo BASE.'/panel/modalidades' ?>" class="btn btn-danger btn-mini"><i class="icon-remove icon-white"></i> Cancelar</a>
                        </div>
                    </div>
                </div>
            </div><!--///header-admin-->

            <div class="form-cad">
                <form class="form-horizontal" method="post">
                    <div class="control-group">
                        <label class="control-label">Nome</label>
                        <div class="controls">
                            <input type="text" value="<?php echo $data->nome; ?>" class="span5" name="nome" placeholder="Nome">
                        </div>
                    </div>

                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn btn-success">Salvar</button>
                        </div>
                    </div>
                </form>
            </div><!--//form-cad-->

        </div><!--//content-->
</div>
<!--//CONTENT-->

<!--//FOOTER-->
<?php $this->render('back/footer'); ?>
