</div><!--//row-fluid-->
</div><!--/fluid-container-->
<hr/>
<div class="container-fluid">
    <div class="row-fluid">
        <footer>
            <p>&copy Copiryght <?php echo date('Y'); ?> - Todos os direitos reservados</p>
        </footer>
    </div>
</div>
<script src="<?php echo BASE ?>/javascript/jquery.js"></script>
<script src="<?php echo BASE ?>/javascript/select2/select2.min.js"></script>
<script src="<?php echo BASE ?>/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo BASE ?>/javascript/datetimepicker/jquery.datetimepicker.js"></script>
<script src="<?php echo BASE ?>/javascript/tinymce/tinymce.min.js"></script>
<script src="<?php echo BASE ?>/javascript/funcoes.js"></script>
</body>
<?php
ob_end_flush();
?>
</html>