<!--//HEADER-->
<?php $this->render('back/header'); ?>

<!--//MENU SDEBAR-->
<div class="span2 menu-sidebar">
<?php $this->render('back/sidebar'); ?>
</div>

<!--//CONTENT -->
<div class="span10">
    <ul class="breadcrumb">
        <li><a href="#">Painel</a> <span class="divider">/</span></li>
        <li class="active">Início</li>
    </ul>

    <div class="msgs">
        <div class="alert alert-danger" style="display: none">
            <a href="#" class="close" data-dismiss="alert">x</a>
            Não foi possível completar a operação
        </div>
    </div>

    <div class="conteudo-admin">
        <div class="list-data span12">

            <div class="estatisticas">
                <ul class="thumbnails">
                    <li class="span4">
                        <div class="thumbnail">
                            <img alt="" src="http://placehold.it/300x200">
                            <div class="caption">
                                <h3>Rótulo para a miniatura</h3>
                                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                <p><a class="btn btn-primary" href="#">Ação</a> <a class="btn" href="#">Ação</a></p>
                            </div>
                        </div>
                    </li>
                    <li class="span4">
                        <div class="thumbnail">
                            <img alt="" src="http://placehold.it/300x200">
                            <div class="caption">
                                <h3>Rótulo para a miniatura</h3>
                                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                <p><a class="btn btn-primary" href="#">Ação</a> <a class="btn" href="#">Ação</a></p>
                            </div>
                        </div>
                    </li>
                    <li class="span4">
                        <div class="thumbnail">
                            <img alt="" src="http://placehold.it/300x200">
                            <div class="caption">
                                <h3>Rótulo para a miniatura</h3>
                                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                <p><a class="btn btn-primary" href="#">Ação</a> <a class="btn" href="#">Ação</a></p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>

        </div><!--//list-data-->
    </div>
</div>
<!--//CONTENT-->

<!--//FOOTER-->
<?php $this->render('back/footer'); ?>
