<ul class="nav nav-tabs nav-stacked">
    <li><a href="<?php echo BASE.'/panel/modalidades' ?>"><i class="icon-th-large"></i> Modalidades</a></li>
    <li><a href="<?php echo BASE.'/panel/licitacoes' ?>"><i class="icon-bookmark"></i> Licitações</a></li>
    <li><a href="<?php echo BASE;?>/panel/usuarios"><i class="icon-user"></i> Usuários</a></li>
    <li><a href="<?php echo BASE.'/panel/usuarios/novo/'.$_SESSION['aut']->id; ?>"><i class="icon-edit"></i> Perfil</a></li>
</ul>